example/.taskmaster/docs/task-11/acceptance-criteria.md
example/.taskmaster/docs/task-11/design-spec.md
example/.taskmaster/docs/task-11/prompt.md
example/.taskmaster/docs/task-11/task.md
example/.taskmaster/docs/task-12/acceptance-criteria.md
example/.taskmaster/docs/task-12/design-spec.md
example/.taskmaster/docs/task-12/prompt.md
example/.taskmaster/docs/task-12/task.md
example/.taskmaster/docs/task-13/acceptance-criteria.md
example/.taskmaster/docs/task-13/design-spec.md
example/.taskmaster/docs/task-13/prompt.md
example/.taskmaster/docs/task-13/task.md
example/.taskmaster/docs/task-14/acceptance-criteria.md
example/.taskmaster/docs/task-14/design-spec.md
example/.taskmaster/docs/task-14/prompt.md
example/.taskmaster/docs/task-14/task.md
example/.taskmaster/docs/task-15/acceptance-criteria.md
example/.taskmaster/docs/task-15/design-spec.md
example/.taskmaster/docs/task-15/prompt.md
example/.taskmaster/docs/task-15/task.md
example/.taskmaster/docs/task-16/acceptance-criteria.md
example/.taskmaster/docs/task-16/design-spec.md
example/.taskmaster/docs/task-16/prompt.md
example/.taskmaster/docs/task-16/task.md
example/.taskmaster/export-session.sh
example/.taskmaster/prompt.md

This PR contains automatically generated documentation for Task Master tasks.
- Comprehensive task overviews (task.md)
- Autonomous AI prompts (prompt.md)
- Technical design specifications (design-spec.md)
- Acceptance criteria (acceptance-criteria.md)
- Model: claude-sonnet-4-20250514
- Task: 999999 (all tasks)
- Branch: docs/task-master-docs-20250709-213954
---
_Automatically generated by Orchestrator Documentation Service_

docs: auto-generate Task Master documentation

---

infra/charts/controller/claude-templates/intake/intake.sh
infra/charts/controller/templates/project-intake-template.yaml

Clean PR from main with only:\n- docs/intake/prd.txt\n- docs/intake/architecture.md\n- intake.sh tweaks (--rules=claude, PRD preview)\nNo other file changes. Supersedes #127, #128, #130, #131.

docs(intake): Discord monitoring (clean PR)

---

input-bridge/src/main.rs

This fixes the docs job hang by ensuring the sidecar opens-writes-closes the FIFO per request.
- Removed persistent writer that prevented EOF
- Added mutex to serialize writes
- Keeps FIFO semantics intact and allows `wait ` to return so PR creation runs

fix(input-bridge): do not hold FIFO open; allow EOF so docs container exits

---

mcp/src/main.rs

The MCP `mcp_cto_input` tool was failing to send messages to running agents because it was using the wrong service discovery approach:
- ❌ **Old approach**: kubectl exec into pods + write to FIFO files  
- ❌ **Service discovery**: Looking for pods with wrong label patterns
- ❌ **Result**: Messages never reached the agents
Meanwhile, direct HTTP calls worked perfectly:
```bash
curl -X POST "http://docs-agent-platform-docs-task-m689h-b7b20c05-bridge.agent-platform.svc.cluster.local:8080/input"
```
Updated the MCP input tool to use the correct architecture:
- ✅ **New approach**: Direct HTTP POST to input bridge services
- ✅ **Service discovery**: Find services with `agents.platform/input=bridge` labels
- ✅ **Routing**: Use `jobType`, `user`, and `name` labels for filtering
- ✅ **Protocol**: …

Fix MCP input tool service discovery

---

infra/images/opencode/Dockerfile
infra/images/opencode/README.md

fix: update OpenAI API key configuration for improved documentation access (#248)

---

.github/workflows/agents-build.yaml
infra/images/opencode/Dockerfile
infra/images/opencode/README.md

This PR adds Open Code as a new agent to the platform:
1. **Open Code Docker Image** ()
- Debian-based runtime for compatibility
- Installs Open Code CLI via official install script
- Supports headless server mode for automated workflows
- Includes comprehensive README with usage examples
2. **GitHub Actions Integration** ()
- Added Open Code to the agent build matrix
- Version tracking via script hash from install URL
- Automatic daily builds with other agents
- **Headless Server Mode**: Can run  for automated workflows
- **Interactive Mode**: Supports  for direct task execution
- **Multi-platform**: Works with both AMD64 and ARM64 architectures
- **Provider Agnostic**: Can use Claude, OpenAI, Google, or local models
- ✅ Docker image builds successfully
- ✅ Open Code CLI installs and …

Add Open Code agent image and build configuration

---

docs/.taskmaster/docs/task-5/acceptance-criteria.md
docs/.taskmaster/docs/task-5/prompt.md
docs/.taskmaster/docs/task-5/task.md

- Remove templated labelSelector usage; use deterministic metadata.name targeting
- Keep JQ extraction with branch fallback and validation
- Update acceptance criteria, prompt, and task guide accordingly

docs(task-5): align correlation docs with supported Argo Events patterns

---

docs/.taskmaster/docs/task-4/acceptance-criteria.md
docs/.taskmaster/docs/task-4/prompt.md
docs/.taskmaster/docs/task-4/task.md

Clarifies implementation agents keep shared workspace; isolates non-implementation agents; updates acceptance criteria and prompt.

docs(task-4): update requirements for conditional PVC naming

---

docs/.taskmaster/docs/task-6/acceptance-criteria.md
docs/.taskmaster/docs/task-6/prompt.md
docs/.taskmaster/docs/task-6/task.md

Add QA-stage docs check under Cleo: classify changes, suggest required docs, upsert PR comment, and block approval until docs updated or rationale provided.

docs(task-6): QA docs-enforcement before approval

---

infra/gitops/resources/github-webhooks/CORRELATION-LOGIC-DOCS.md
infra/gitops/resources/github-webhooks/DEPLOYMENT-GUIDE.md
infra/gitops/resources/github-webhooks/TASK-5-FINAL-REPORT.md
infra/gitops/resources/github-webhooks/TASK-5-IMPLEMENTATION-SUMMARY.md
infra/gitops/resources/github-webhooks/TASK-5-VERIFICATION.md
infra/gitops/resources/github-webhooks/enhanced-correlation-sensor.yaml
infra/gitops/resources/github-webhooks/test-correlation-logic.sh
infra/gitops/resources/github-webhooks/test-output.txt
infra/gitops/resources/github-webhooks/test-payloads/test-webhook-payloads.json

- Add enhanced correlation sensor with multi-event support
- Implement task ID extraction with fallback logic
- Create deterministic workflow targeting (play-task-{id}-workflow)
- Add comprehensive test suite with 7 passing test cases
- Include complete documentation and deployment guides
- Support PR created, labeled, approved, and push events
- Implement remediation logic for implementation agent pushes
- Validate all acceptance criteria with 100% compliance
Test Results:
- All 7 automated tests passing
- Handles edge cases: malformed labels, missing IDs, duplicates
- Performance: <100ms extraction, <500ms correlation
- Security: Input validation, no code injection risks
Files created:
- enhanced-correlation-sensor.yaml: Main sensor implementation
- test-correlation-logic.sh: Automated …

feat(task-5): implement GitHub webhook correlation logic

---

controller/src/tasks/code/agent.rs
controller/src/tasks/github.rs
controller/src/tasks/workflow.rs
scripts/test-stage-transitions.sh

Addresses lint and test failures introduced by merge of #305. Fixes Clippy warnings and adjusts failing test for new logic.

Fix broken tests post PR #305

---

.gitignore
infra/secret-store/jupiter-external-secrets.yaml

- Add jupiter-external-secrets.yaml for Solana GRPC credentials
- Create jupiter namespace and ExternalSecret configuration
- Add sol.env to .gitignore to protect credentials
- Sync SOLANA_GRPC_ENDPOINT and SOLANA_RPC_API_KEY from secret-store

feat: add Jupiter external secrets configuration

---

.gitignore
infra/gitops/applications/jupiter.yaml

- Add 'charts-repo/' to .gitignore to exclude local development files from version control

feat: add Jupiter to infra

---

cto-config.json
docs/cleo-to-tess-flow.md
infra/gitops/resources/github-webhooks/play-workflow-sensors.yaml
infra/gitops/resources/github-webhooks/stage-aware-resume-sensor.yaml

- Changed repository and docsRepository in cto-config.json to reflect new naming conventions.
- Improved task ID extraction logic in play-workflow-sensors.yaml and stage-aware-resume-sensor.yaml to be case-insensitive and handle JSON encoding, ensuring better compatibility with PR labels.

fix: update repository references and enhance task ID extraction in webhooks

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs

- Updated quality review steps to include fixing issues found during checks.
- Added a summary comment feature that posts a review summary to the PR, detailing the quality checks performed and their results.
- Revised success criteria to ensure quality checks must pass after any fixes for approval.
This improves the clarity and accountability of the code review process, ensuring all quality standards are met before moving to QA.

feat: enhance quality review process in Cleo

---

infra/charts/controller/claude-templates/docs/container.sh.hbs

This PR adds XML file generation capability to the docs container script, enabling enhanced LLM processing alongside the existing task.txt files.
- Modified  to generate  files
- XML format follows the research-backed structure from  for optimal Claude performance
- Maintains backward compatibility with existing  generation
- **Structured task metadata**: id, title, description, priority, status, dependencies
- **Technical specifications**: Generic specs that apply to all tasks
- **Implementation details**: Uses existing task details field
- **Acceptance criteria**: Standard criteria for quality assurance
- **Test strategy**: Incorporates existing testStrategy field
- **Instructions**: Comprehensive guidance for LLM processing
- **Improved LLM performance**: XML format is 15-20% more …

feat: add XML file generation to docs container script

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs

Tess and Cleo containers were hanging after completing their work, preventing workflows from progressing to the next stage.
Added explicit `exit $CLAUDE_EXIT_CODE` at the end of both container scripts, consistent with Rex's exit handling.
- **Tess**: Added proper exit with Claude's exit code after completion
- **Cleo**: Added proper exit with Claude's exit code after completion
- Both now include completion banners before exiting
This fix ensures:
1. Containers exit cleanly after completing their work
2. Workflows can progress to the next stage
3. No hanging processes blocking the pipeline
4. Consistent exit behavior across all agents
This is the same fix we applied to Rex earlier.

fix: ensure Tess and Cleo containers exit properly

---

docs/github-projects-integration-design.md
infra/charts/controller/values.yaml

- Updated Tess system prompt to clearly state she should exit after submitting review
- Added explicit instruction: 'After submitting your PR review, your work is complete. Exit immediately.'
- This prevents containers from hanging after completing QA work
- Mirrors the same pattern used for Rex container exit fixes

fix: ensure Tess exits after submitting PR review

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-rex.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs
infra/charts/controller/values.yaml
infra/runner-cache/cache-pvc.yaml
infra/runner-cache/values.yaml

Container termination issues affecting all agents (Rex, Cleo, Tess) where:
- Agents complete their work successfully 
- But containers don't properly terminate
- Pods remain in Running state indefinitely
- Workflow progression is blocked
From debugging the stuck Tess pod ():
1. **Agent work completed successfully**: Tess finished comprehensive QA testing and approved PR #96
2. **Sidecar shutdown failed silently**: No shutdown logs visible, sidecar still listening on port 8080
3. **Containers didn't exit**: Both claude-code and sidecar containers remained running
Enhanced container termination logic for all agents:
- **Retry logic**: 3 attempts with 2-second delays
- **Timeout protection**: 5-second curl timeout per attempt
- **Force termination fallback**:  if graceful shutdown fails
- …

fix: Enhanced container termination for Rex, Cleo, and Tess agents

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs
infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml

🔧 AUTHENTICATION FIX:
- Fixed broken REPO_HTTP_URL construction in Tess and Cleo
- Removed usage of undefined variables REPO_OWNER and REPO_NAME
- Now uses REPO_HTTP_URL from authentication verification section
- Aligns with Rex's proven working approach
🔧 TEMPLATE ESCAPING FIX:
- Fixed template escaping for all workflow.parameters.* variables in CodeRun manifests
- Applied Golang template escaping (backticks) to prevent early resolution
- Fixed variables: service, task-id, github-owner, github-repo, docs-repo
Previously:
- git clone was failing due to malformed URLs like 'https://x-access-token:token@github.com//.git'
- Task completion workflows failed with 'failed to resolve {{workflow.parameters.service}}'
Now:
- Authentication uses consistent credential store approach across all …

fix: resolve critical authentication and template issues

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-rex.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs
infra/charts/controller/claude-templates/code/container.sh.hbs
infra/images/runtime/Dockerfile

- Added checks to ensure the Rust environment is properly set up in multiple container scripts (cleo, rex, tess, and main).
- Included sourcing of Rust environment from both user and root directories.
- Added verification for the availability of `rustup` and `cargo`, with informative output for each step.
- Updated Dockerfile to ensure Rust environment variables are set in shell profiles and created a global setup script for Rust environment.
This improves the reliability of Rust toolchain availability across different containers.

Enhance Rust environment setup in container scripts

---

ROADMAP.md

- Added a section for recently implemented features, including GitHub webhooks integration with Argo workflows.
- Revised immediate priorities to focus on agent-centric tool configuration and parallel task execution.
- Enhanced details on core platform enhancements and future vision, including multi-agent orchestration capabilities.
- Improved clarity on contribution areas to align with current development focus.

docs: Update ROADMAP.md with recent implementations and future priorities

---

README.md

This PR transforms the CTO repository README from a purely technical document into an engaging, character-driven narrative that showcases our AI agent dream team while preserving all technical information.
**🎯 Hero Section**
- Added 5D Labs branding with logo and badges
- Community links (Discord, GitHub Stars, License, Kubernetes)
- Clear value proposition: *GitOps for AI Agents - Where Code Ships Itself*
**👥 AI Agent Team Introduction**
- **Morgan** (Knowledge Architect) - Documentation generation via `docs()`
- **Rex** (Backend Powerhouse) - Rust/backend implementation via `code()`
- **Blaze** (Interface Maestro) - Frontend/UX development 
- **Cleo** (Quality Guardian) - Code review and QA in `play()` workflows
- **Tess** (Testing Genius) - Comprehensive testing and validation
- …

✨ Transform README with engaging character-driven narrative

---

README.md

Clean up the Development Status section by removing emoji bullet points (✅ and 🔄) for better formatting and professional appearance. This change only affects the visual presentation - all content remains the same.

Remove emoji bullet points from Development Status section

---

README.md

Clean up the Development Status section by replacing bullet points with emoji status indicators:
✅ Completed items (Core platform, MCP server, Kubernetes controllers, GitHub Apps)
🔄 In-progress items (Documentation improvements, Public release preparation)
This provides clearer visual status indication without redundant bullet points.

Replace bullet points with emoji status indicators

---

infra/gitops/applications/mailu-tcp-endpoints.yaml
infra/gitops/applications/mailu.yaml
infra/gitops/resources/mailu-tcp-endpoints.yaml

- Change the include line in mailu-tcp-endpoints.yaml to use quotes for consistency.
- This minor adjustment improves YAML parsing and readability.

fix(mailu): update include syntax for mailu-tcp-endpoints.yaml

---

infra/gitops/applications/mailu.yaml

- Set global logLevel: DEBUG for all Mailu services
- Set admin.logLevel: DEBUG for detailed admin service logs
- Should provide more detailed information about database connections and startup issues

feat(mailu): enable DEBUG logging for troubleshooting

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs

- Update mindset: code is guilty until proven innocent
- Require 95% minimum test coverage (reject if less)
- 100% acceptance criteria compliance (99% = failure)
- Reject for ANY quality issue (TODOs, commented code, unclear names)
- Test exhaustively including edge cases, performance, security
- Be pedantic, nitpicky, and relentless
- Better to reject good code than approve bad code
- List EVERY issue no matter how minor
- When in doubt, always REQUEST CHANGES

feat: make Tess ultra-strict and extremely critical in QA reviews

---

docs/engineering/agent-remediation-loop-design.md
infra/charts/controller/claude-templates/code/container-rex.sh.hbs

- Introduce critical task isolation guidelines to ensure focus on assigned tasks
- Emphasize the importance of ignoring all other tasks and existing code
- Include detailed instructions for confirming task assignment before starting work
- Update prompt prefix to reflect new isolation requirements and toolman guidance

feat: enhance task isolation instructions for implementation agents

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs

- Removed test writing from Cleo (delegated to Tess)
- Added comprehensive test writing responsibilities to Tess
- Added Kubernetes cluster access verification for Tess
- Included proven CI/CD templates in Cleo's instructions:
* Runtime-only Dockerfile pattern
* CI workflow with caching and clippy pedantic
* Deploy workflow with k8s-runner and sccache
- Updated Tess to verify deployment pipelines
These changes ensure proper separation of concerns between agents
and standardize CI/CD practices across all projects.

feat: enhance agent templates with CI/CD best practices

---

docs/FINAL_TECHNOLOGY_STACK.md
docs/PROPRIETARY_REPLACEMENTS.md
docs/TUNNELING_STRATEGY.md

- Renamed document from "Proprietary Component Replacement Strategy" to "Component Integration Strategy" to reflect a broader focus on integrating open-source tools.
- Consolidated and clarified the technology stack, emphasizing the use of NGrok and Cloudflare for tunneling while replacing Twingate with WireGuard for VPN solutions.
- Streamlined sections to enhance readability and focus on implementation strategies, including detailed WireGuard configuration and automated user management.
- Removed outdated alternatives and added a new section for simple port forwarding for solo developers.

refactor: update proprietary component replacement strategy to integration strategy

---

docs/CTO_PLATFORM_ENHANCEMENTS_OVERVIEW.md

- Revised the document to reflect the addition of a sixth mini-project focused on Platform Packaging, detailing its objectives, key components, and timeline.
- Adjusted project structure to include the new GitHub integration enhancements directory.
- Updated the conclusion to emphasize the modular design and future distribution capabilities of the platform.

docs: update CTO Platform Enhancements overview to include new mini-project and packaging details

---

docs/CTO_PLATFORM_ENHANCEMENTS_OVERVIEW.md
docs/landing-page-creation/architecture.md
docs/landing-page-creation/prd.txt
docs/mcp-tool-selection-enhancement/architecture.md
docs/mcp-tool-selection-enhancement/prd.txt
docs/telemetry-monitoring-enhancement/architecture.md
docs/telemetry-monitoring-enhancement/prd.txt

- Revised the document to reflect the addition of a seventh mini-project focused on Telemetry Monitoring Enhancement, detailing its objectives, key components, and timeline.
- Updated project structure to include the new platform-packaging directory.
- Adjusted the conclusion to highlight the importance of comprehensive monitoring in the platform's evolution.

docs: update CTO Platform Enhancements overview to include new telemetry monitoring enhancement

---

docs/agent-tool-configuration/architecture.md
docs/agent-tool-configuration/prd.txt

- Introduced standalone agent workflows for bug remediation, feature requests, and CI failure remediation, detailing their requirements and success criteria.
- Updated architecture documentation to reflect the new tools and their integration into existing workflows, including automated processes for issue detection and remediation.
- Enhanced PRD to outline the functionality and expected outcomes for each agent type, ensuring seamless integration with current systems.

docs: enhance agent tool configuration with standalone agent workflows

---

infra/charts/controller/claude-templates/code/container-tess.sh.hbs

- Simplified CI status checks by removing redundant commands and enhancing clarity.
- Added alternative method to check workflow runs for failures or pending statuses.
- Ensured that only successful checks allow for PR approval, improving the verification process.

docs: update CI verification commands in container-tess.sh.hbs

---

infra/charts/controller/claude-templates/code/container-tess.sh.hbs

- Fixed 'fix: command not found' error caused by malformed UTF-8 characters
- Replaced fancy box drawing characters with simple ASCII art
- Ensures shell doesn't interpret diagram content as commands
- Resolves Tess container startup failures

fix: replace corrupted box drawing characters in Tess container script

---

infra/gitops/resources/github-webhooks/remediation-feedback-sensor.yaml

- Fix regex filter to use array format for Argo Events compatibility
- Both fixes address JSON unmarshal errors in Argo Events controller

fix: Correct sensor filter values to use arrays instead of strings

---

controller/src/remediation/mod.rs
controller/src/remediation/state.rs
controller/src/tasks/types.rs

Build comprehensive ConfigMap-based state tracking for remediation iterations, feedback history, and workflow state management in the Rust controller.
- **RemediationState** - Main workflow state with PR number, task ID, iteration count, status, and metadata
- **FeedbackEntry** - Individual feedback history entries with structured data and status tracking  
- **ActiveRun** - Information about currently running CodeRun/DocsRun resources
- **RemediationStatus** - Enum for workflow status (WaitingForFeedback, InProgress, Completed, etc.)
- Persistent state storage using Kubernetes ConfigMaps
- Automatic naming convention: remediation-state-pr-{pr_number}-task-{task_id}
- JSON serialization of complete state objects
- Thread-safe operations with proper error handling
- initialize_state() - …

feat: Implement State Management System for Agent Remediation Loop (Task 4)

---

infra/charts/controller/claude-templates/code/container-rex.sh.hbs

- Removes .agent_done file at container startup
- Prevents premature sidecar shutdown on subsequent runs
- Enables running same task multiple times on same PVC
- Critical for Rex implementation retries and remediation cycles

fix: clean up sentinel file at startup to enable sequential task runs

---

infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs

- Remove .cleo-complete marker at Cleo startup
- Remove .tess-complete marker at Tess startup
- Prevents stale markers from affecting sequential runs
- Enables running same task multiple times on same PVC

fix: clean up agent completion markers at startup

---

infra/charts/controller/claude-templates/code/client-config.json.hbs
infra/charts/controller/claude-templates/code/coding-guidelines.md.hbs
infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
infra/charts/controller/claude-templates/code/container-rex-remediation.sh.hbs
infra/charts/controller/claude-templates/code/container-rex.sh.hbs
infra/charts/controller/claude-templates/code/container-tess.sh.hbs
infra/charts/controller/claude-templates/code/container.sh.hbs
infra/charts/controller/claude-templates/code/hooks/stop-code-pr-creation.sh.hbs
infra/charts/controller/claude-templates/docs/claude.md.hbs
infra/charts/controller/claude-templates/docs/container.sh.hbs
infra/charts/controller/claude-templates/docs/hooks/after-file-saved.sh.hbs
infra/charts/controller/claude-templates/docs/toolman-catalog.md.hbs
infra/charts/controller/templates/agents-configmap.yaml
infra/charts/controller/templates/claude-templates-configmap.yaml
infra/charts/controller/templates/rbac.yaml
infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
infra/gitops/rbac/argo-workflow-permissions.yaml

- Added cleanup for .agent_done and .tess-complete files at the start of the container script
- Prevents sidecar shutdown and stale markers from affecting sequential task executions
- Ensures proper environment setup for Rust projects by including formatting instructions

fix: enhance startup script to clean up sentinel and completion markers

---

docs/remediation-loop-analysis.md
infra/charts/controller/claude-templates/code/container-tess.sh.hbs
infra/gitops/resources/github-webhooks/remediation-feedback-sensor.yaml

- Expand sensor event monitoring to catch PR reviews, check runs, and manual triggers
- Fix Tess MCP server communication by connecting to k8s-mcp service in mcp namespace
- Update Tess system prompt to use structured '🔴 Required Changes' format for sensor recognition
- Add remediation state tracking with feedback type and iteration metadata
- Implement proper parameter extraction for different event types (comment/review/check-run)
- Update PR review format to match sensor expectations
These fixes address the critical gaps identified in remediation-loop-analysis.md:
- PR review feedback now triggers remediation (was only catching issue comments)
- Tess feedback format matches sensor expectations
- MCP server communication works across namespaces
- Manual remediation triggers supported
- …

fix: implement comprehensive remediation loop fixes

---

infra/gitops/resources/github-webhooks/remediation-feedback-sensor.yaml

- Eliminated unnecessary conditions from the trigger configuration in the remediation feedback sensor YAML file, streamlining the event handling process.

fix: remove redundant conditions from remediation feedback sensor

---

.github/workflows/agents-build.yaml
cli-agnostic-platform/architecture.md
cli-agnostic-platform/integration-plan.md
cli-agnostic-platform/prd.txt
controller/src/cli/adapter.rs
controller/src/cli/bridge.rs
controller/src/cli/discovery.rs
controller/src/cli/mod.rs
controller/src/cli/router.rs
controller/src/cli/session.rs
controller/src/cli/types.rs
controller/src/crds/coderun.rs
controller/src/lib.rs
controller/src/tasks/code/resources.rs
controller/src/tasks/code/templates.rs
controller/src/tasks/config.rs
controller/src/tasks/workflow.rs
infra/charts/controller/templates/coderun-template.yaml
infra/charts/controller/values.yaml
infra/images/codex/Dockerfile
infra/images/codex/health-check.sh
infra/images/opencode/Dockerfile.local

- Fix Codex Docker image to use actual @openai/codex CLI instead of SDK
- Fix OpenCode Docker image to create required cache directory
- Update GitHub Actions workflow for correct Codex npm package detection
- Add comprehensive CLI feature analysis and integration plan
- Document MCP compatibility across Claude, Codex, and OpenCode
This establishes the foundation for multi-CLI support while maintaining
backward compatibility with existing Claude workflows.

feat: CLI-agnostic platform discovery and Docker fixes

---

cto-config.json
mcp/src/main.rs
mcp/src/tools.rs

- Added CLI and model fields to agent configurations in cto-config.json for improved agent-specific settings.
- Updated MCP to reflect changes in agent configuration, including renaming local_servers for clarity.
- Removed unused code related to the code workflow and export functionality, streamlining the tool schemas.
- Adjusted job and stop_job schemas to focus on Argo workflows, enhancing clarity and usability.

feat: enhance agent configuration in CTO and MCP

---

mcp/src/main.rs

- Fixed incorrect return statement in JSON extraction logic
- Added debug logging to help diagnose API response issues
- Improved prompt to ensure Claude returns only JSON
- Added proper error handling for malformed responses
The issue was that the return statement inside the JSON extraction was incorrectly trying to return from a match arm, causing extraction to always fail when Claude included any text around the JSON.

fix: Fix JSON extraction from Claude API response in intelligent_ingest

---

cto-config-example.json
cto-config.json
cto-config.template.json
infra/charts/controller/values.yaml
mcp/src/main.rs
mcp/src/tools.rs

- Added `docs_ingest` configuration to `cto-config.json`, `cto-config-example.json`, and `cto-config.template.json` for improved documentation ingestion workflows.
- Updated local server tools in `cto-config.json` and `cto-config-example.json` to include `directory_tree`.
- Renamed `intelligent_ingest` to `docs_ingest` in the codebase for consistency and clarity.
- Enhanced the handling of the `docs_ingest` tool in the main application logic and updated related schemas in `tools.rs`.

feat: update configuration for docs ingestion and enhance tool capabilities

---

mcp/Cargo.lock
mcp/Cargo.toml
mcp/src/main.rs

- Replace manual temporary file management with Rust's tempfile crate
- Ensure temporary files are automatically cleaned up when they go out of scope
- Prevent resource leaks when curl commands fail or when auto_execute is false
- Add proper error handling for temporary file operations
- Maintain security improvements from previous shell injection fix

fix: resolve temporary file leak in document ingestion

---

infra/gitops/applications/doc-server.yaml

- Add topic_keywords and category_keywords to BirdEye query tool for DeFi API filtering
- Add comprehensive keyword mappings to Solana query tool for blockchain topics
- Enhance Jupiter query tool with trading and liquidity keyword mappings
- Add metadataHints to Cilium, Talos, Meteora, Raydium, and eBPF query tools
- Include Rust best practices and general Rust query keyword mappings
- Enable accurate metadata extraction and filtering across all documentation sources
- Configuration-driven system will automatically pick up these changes on deployment
This enables the enhanced metadata system to properly score content against configured keywords and assign metadata based on the highest-scoring matches, improving search accuracy and filtering capabilities.

feat: Enhance docs metadata system with comprehensive keyword mappings

---

infra/gitops/databases/trader-postgres.yaml
infra/gitops/databases/trader-questdb.yaml

This PR adds a new PostgreSQL database instance specifically configured for the trader application.
- **Added**  with trader-specific configuration
- **Configured** standard PostgreSQL 16 instance (no vector extensions)
- **Set up** trader_user with appropriate permissions for trader_db
- **Enabled** connection pooling and high availability (2 instances)
- **Included** useful PostgreSQL extensions:
- uuid-ossp for UUID generation
- hstore for key-value storage
- pg_trgm for text similarity
- pgcrypto for encryption functions
- btree_gin/btree_gist for advanced indexing
- **Database**: trader_db owned by trader_user
- **Resources**: 1-4Gi memory, 500m-2000m CPU
- **Storage**: 50Gi with local-path storage class
- **Users**: trader_user, readonly, admin
- **Extensions**: Standard PostgreSQL …

feat: Add trader PostgreSQL database configuration

---

controller/src/tasks/code/templates.rs

- Improved agent configuration retrieval by adding detailed debug logging for matched agent configurations.
- Implemented logic to handle client configuration in three scenarios: using verbatim clientConfig, generating clientConfig from tools, or returning a minimal JSON object when no configurations are found.
- Ensured robust error handling for serialization failures, providing clearer error messages for configuration issues.

feat: enhance client configuration handling in CodeTemplateGenerator

---

controller/src/tasks/code/templates.rs
infra/charts/controller/values.yaml

- Enhanced the handling of local server configurations by safely managing missing or empty configurations.
- Updated logic to convert existing local server structures to JSON, ensuring robustness in configuration retrieval.
- Simplified the fallback mechanism to return an empty JSON object when no local servers are configured.

feat: improve local server configuration handling in CodeTemplateGenerator

---

cli-agnostic-platform/architecture.md
controller/src/bin/test_templates.rs
controller/src/cli/adapters/codex.rs
controller/src/tasks/config.rs
cto-config-example.json
cto-config.json
cto-config.template.json
docs/multi-cli-integration-design.md
infra/charts/controller/values.schema.json
infra/charts/controller/values.yaml
mcp/src/main.rs

This commit updates the model version from gpt-4.1-mini to gpt-5-codex across various configuration files, including cto-config.json, cto-config-example.json, and related templates. This change ensures that the latest model is utilized for code implementation workflows, enhancing performance and capabilities.

feat: update model version in configuration files to gpt-5-codex

---

controller/src/crds/coderun.rs
infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
mcp/src/main.rs

This commit updates the workflow templates to include additional parameters for CLI and model configurations for implementation, quality, and testing agents. The model identifier in the CodeRunSpec struct is also clarified to specify the expected format. These changes improve the flexibility and clarity of the workflow execution, allowing for better integration with various CLI implementations.

feat: enhance model and CLI parameters in workflow templates

---

infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml

This commit enhances the GitOps sensor configuration by introducing additional parameters for implementation, quality, and testing CLI and model settings. It ensures backward compatibility by providing default values when specific parameters are not set. These updates improve the flexibility and clarity of the workflow execution, facilitating better integration with various CLI implementations.

feat: add CLI and model parameters for implementation, quality, and testing agents in GitOps sensor
