- controller/core/src/tasks/code/resources.rs
- controller/core/src/tasks/docs/resources.rs
- controller/mcp/src/main.rs
- infra/charts/controller/templates/coderun-template.yaml
**Problem**: All task submissions failing with "manifest must be valid yaml" error
**Root Cause**: Go templates cannot access parameter names with hyphens using dot notation
**Solution**: Use `index` function to properly access `task-requirements` parameter
```yaml
{{- if workflow.parameters.task-requirements }}
taskRequirements: "{{workflow.parameters.task-requirements}}"
{{- end }}
```
```yaml
{{- if ne (index workflow.parameters "task-requirements") "" }}
taskRequirements: "{{index workflow.parameters "task-requirements"}}"
{{- end }}
```
- ✅ Fixes all task submission failures
- ✅ Clean single-file change
- ✅ No linting errors
- ✅ Ready for immediate ArgoCD deployment
**Critical for restoring platform functionality** 🚀
> 🚨 CRITICAL: Fix Argo workflow parameter syntax for task submissions

- infra/images/cursor-agent/Dockerfile
- Move installed cursor-agent to /usr/local/bin so command is available in non-interactive builds\n- Wire cursor-agent job built output from set-built step to fix summary reporting\n\nFollow-up to #89.
> fix(cursor-agent): installer path + CI summary outputs

- infra/charts/controller/values.yaml
- infra/telemetry/values/claude-code-telemetry.yaml
- Changed image repository from `ghcr.io/5dlabs/cto/claude-code` to `ghcr.io/5dlabs/cto/claude` in both `infra/charts/controller/values.yaml` and `infra/telemetry/values/claude-code-telemetry.yaml`.
- Cleaned up trailing spaces and ensured consistent formatting across the files.
This update aligns the image repository with the current naming convention and improves YAML file formatting.
> Update image repository in controller and telemetry values.yaml files

- infra/charts/controller/claude-templates/intake/intake.sh
- Remove explicit --output .taskmaster/tasks/tasks.json from intake script\n- Avoids error when override path doesn't exist\n- TaskMaster CLI creates tasks.json at its default path and later steps proceed
> fix(intake): rely on task-master default output for parse-prd

- infra/charts/controller/claude-templates/intake/intake.sh
Use same Claude CLI flags as code/docs templates to avoid stream-json/verbose error.\n\n- claude -p --output-format stream-json --verbose --model "" /tmp/review-prompt.md\n- Scope: intake container script only
> fix(intake): align Claude CLI flags (-p, --verbose, stream-json)

- docs/intake/architecture.md
- docs/intake/prd.txt
- infra/charts/controller/claude-templates/intake/intake.sh
- Restore full monitoring docs under docs/intake (single source of truth)\n- Remove root duplicates to prevent intake confusion\n- Intake script: preview PRD/architecture on start; init TaskMaster with --rules=claude\n\nFollow-up to #126 (installation lookup hardening). Merge to main for Argo to pick up.
> docs(intake): restore monitoring PRD/architecture; intake uses --rules=claude and previews PRD

- controller/src/tasks/docs/resources.rs
- infra/charts/controller/claude-templates/docs/container.sh.hbs
- infra/charts/controller/values.yaml
Summary\n- Prevent docs job hang by starting Claude in background, writing initial user turn to FIFO via persistent fd 9, then closing the writer and waiting.\n- Add input-bridge sidecar for DocsRun jobs when agent.inputBridge.enabled is true, using configured image and port; create/update headless Service for discovery.\n\nDetails\n- Files\n  - infra/charts/controller/claude-templates/docs/container.sh.hbs\n  - controller/src/tasks/docs/resources.rs\n- Sidecar uses env FIFO_PATH=/workspace/agent-input.jsonl and PORT from config.\n- Headless Service: <job-name>-bridge with agents.platform/* labels for discovery.\n\nConfig\n- Enable in chart values: agent.inputBridge.enabled=true and set agent.inputBridge.image.repository/tag and port.\n\nTest Plan\n1) Apply controller with inputBridge …
> fix(docs): prevent FIFO hang; add input-bridge sidecar to DocsRun when enabled

- controller/src/tasks/code/resources.rs
- controller/src/tasks/docs/resources.rs
Summary\n- Add pod-level securityContext to CodeRun and DocsRun Jobs: runAsUser:1000, runAsGroup:1000, fsGroup:1000, fsGroupChangePolicy: OnRootMismatch.\n- Mirrors StatefulSet behavior where workspace access is known-good.\n\nRationale\n- Ensures sidecar (input-bridge) and main container share GID-based access to /workspace and FIFO without relying on world-writable perms.\n- Complements existing FIFO creation and retry logic.\n\nFiles\n- controller/src/tasks/code/resources.rs\n- controller/src/tasks/docs/resources.rs\n\nTest Plan\n- Deploy controller; submit CodeRun and DocsRun; verify pod spec includes securityContext at pod level, both containers run as uid/gid 1000.\n- Confirm input-bridge opens FIFO and messages flow.\n\nNotes\n- No change to container images; controller update …
> feat(controller): align Job pod securityContext with STS for workspace access

- docs/engineering/issues/sidecar-io-hang-2025-08-12.md
- infra/charts/controller/claude-templates/code/container.sh.hbs
- Prefer routing initial prompt via sidecar HTTP (/input) which opens-writes-closes\n- Fallback keeps FIFO short-lived: open, write, close\n- Optional HANG_DIAG_SECONDS env triggers non-invasive diagnostics (no kill)\n- Root cause suspected: long-lived writer FD kept open\n- Sidecar Rust impl opens per request and closes; unchanged
> docs: catalog sidecar IO hang + fix FIFO writer handling in code job

- infra/gitops/applications/fluent-bit.yaml
Adds Fluent Bit as a DaemonSet (managed via Argo CD) to tail /var/log/containers and forward logs to the OpenTelemetry Collector (OTLP/HTTP 4318). The collector already exports logs to VictoriaLogs.\n\nDetails:\n- Chart: fluent-bit (telemetry namespace)\n- Inputs: tail CRI logs from /var/log/containers/*\n- Filters: kubernetes metadata enrichment\n- Output: opentelemetry -> otel-collector.telemetry.svc:4318 /v1/logs\n- No CRD changes required; relies on existing otel-collector and victoria-logs apps\n\nAfter merge:\n- Argo will deploy the DaemonSet\n- Validate logs in Grafana Explore (VictoriaLogs datasource) or via VL HTTP API.
> telemetry(logs): ship container stdout to VictoriaLogs via OTEL (Fluent Bit DaemonSet)

- infra/gitops/projects/platform-project.yaml
Fixes Argo CD InvalidSpecError for `fluent-bit` Application:
InvalidSpecError: application repo https://fluent.github.io/helm-charts is not permitted in project 'platform'
Changes:
- Add `https://fluent.github.io/helm-charts` to `spec.sourceRepos` in `infra/gitops/projects/platform-project.yaml`.
Notes:
- This unblocks the `infra/gitops/applications/fluent-bit.yaml` Application which sources the `fluent-bit` chart from the Fluent Helm repo.
- No other changes required; destinations already include `telemetry` namespace.
Once merged to `main`, Argo CD should sync the Fluent Bit app successfully. [[memory:5806097]][[memory:6133257]]
> Allow Fluent Bit Helm repo in platform AppProject

- infra/gitops/applications/fluent-bit.yaml
Co-authored-by: Jonathon Fritz <j@jonathonfritz.com>
> argocd: allow Fluent Bit Helm repo in platform AppProject (fix InvalidSpecError for fluent-bit app) (#173)

- infra/cluster-config/telemetry-namespace.yaml
- infra/gitops/applications/telemetry-namespace.yaml
Fix Fluent Bit pod creation failures due to Pod Security Admission baseline policy blocking hostPath volumes.
Error:
- pods are forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "varlog", "varlibdockercontainers", "etcmachineid")
Changes:
- Add `infra/cluster-config/telemetry-namespace.yaml` to manage `telemetry` namespace with privileged PSA labels.
- Add Argo CD Application `infra/gitops/applications/telemetry-namespace.yaml` to apply labels via GitOps.
Notes:
- This permits hostPath volumes required by Fluent Bit.
- `fluent-bit` Application already has Replace=true to handle DS immutability.
Once merged to `main`, Argo CD will label the namespace and Fluent Bit pods should be created successfully. [[memory:6133257]] [[memory:5806097]]
> Manage telemetry namespace PSA to allow Fluent Bit hostPath volumes

- infra/gitops/projects/platform-project.yaml
- Allow cluster-scoped GatewayClass and IngressClass
- Allow namespaced Gateway/HTTPRoute, fixing sync failures for ngrok-gateway and github-webhooks
After merge, Argo should sync ngrok-operator, ngrok-gateway, and github-webhooks cleanly.
> ArgoCD: permit Gateway API + IngressClass in platform AppProject

- infra/gitops/resources/github-webhooks/kustomization.yaml
- Exclude  from 
- Keeps the demo Sensor manifest in repo for reference, but stops it from being applied
- No more demo pods will be created on GitHub org events
Can re-enable later by adding  back to the kustomization.
> Disable demo Sensor (keep code, stop creating pods)

- infra/charts/controller/claude-templates/intake/intake.sh
- Replace branch naming from `intake/-...` to `intake--...` to avoid conflicts when a flat ref `refs/heads/intake` exists.
- Uses sanitized, lowercase `` which is already computed earlier in the script.
This prevents failures like: \n> cannot lock ref 'refs/heads/intake/Docs-YYYYMMDD-HHMMSS': 'refs/heads/intake' exists; cannot create 'refs/heads/intake/Docs-...'
After merge to main and Argo CD rollout, re-run intake for docs.
> fix(intake): avoid branch prefix collision by using hyphen and sanitized project name

- cto-config.json
- docs/.taskmaster/docs/task-1/acceptance-criteria.md
- docs/.taskmaster/docs/task-1/task.md
- infra/charts/controller/values.yaml
This PR fixes several issues with Task 1 and the controller configuration:
1. **Linting Error**: Fixed Helm linting error by commenting out  in 
2. **GitHub App Creation Requirements**: Added explicit requirements for org-level GitHub App creation
3. **Task Clarity**: Made GitHub App creation a critical, non-optional requirement
- ****: Commented out  to fix linting
- Fixed previous ServiceAccount configuration issues from feature/coderun-serviceaccount
- ****: 
- Added new section "2.1. GitHub App Creation (Organization Level)"
- Made GitHub App creation **CRITICAL** with explicit validation
- Added specific validation URLs and requirements
- ****:
- Added prominent "CRITICAL REQUIREMENT: GitHub App Creation" section
- Made it explicit that creating GitHub Apps is mandatory
- Added …
> Fix Task 1 GitHub App Requirements and ServiceAccount Linting

- docs/.taskmaster/docs/task-1/acceptance-criteria.md
- docs/.taskmaster/docs/task-1/task.md
- infra/images/runtime/Dockerfile
- Add explicit Argo Workflows CLI verification to prerequisites
- Clarify difference between argo (workflows) and argocd (CD) CLIs
- Make GitHub App creation CRITICAL and mandatory during task execution
- Fix Dockerfile to use correct argo version syntax (remove --client flag)
- Prevent agents from marking task complete without creating GitHub Apps
> docs: clarify Argo CLI availability and make GitHub App creation mandatory

- mcp/src/main.rs
Fixed clippy/linter warnings and errors in the MCP codebase and investigated the GitHub App authentication failure we observed in the docs job.
- **Unused variable**: Removed unused task_id parameter in handle_send_job_input function
- **Borrow-of-moved-value**: Fixed by saving response.status() before calling response.text()
- **Result**: All clippy warnings and errors now resolved
Investigated the GitHub App authentication failure in the docs job:
The docs job authentication failure was NOT due to broken JWT generation code. The current container templates already have correct JWT generation with proper headers.
The docs job was using an old container image that was built before the JWT fixes were applied. Since PR #229 updated the image names (removing /cto/), new jobs will …
> Fix MCP linter errors and authentication analysis

- .github/workflows/agents-build.yaml
- .github/workflows/develop-deploy.yaml
- .github/workflows/runner-builld.yaml
All self-hosted runners are offline in  trying to pull:
- `ghcr.io/5dlabs/rust-builder:latest` (doesn't exist yet)
Classic chicken-and-egg problem:
1. **Self-hosted runners down**: Can't pull new image names (don't exist)
2. **Workflows can't run**: No available runners  
3. **New images can't build**: Workflows are stuck in queue
4. **Cycle continues**: No way forward with current setup
**Temporarily use GitHub hosted runners** for critical image-building workflows:
- `runs-on: ubuntu-latest` instead of `runs-on: [k8s-runner]`
- `.github/workflows/agents-build.yaml` - Build container images (most critical)
- `.github/workflows/develop-deploy.yaml` - Deployment workflows
- `.github/workflows/runner-builld.yaml` - Runner cycling
1. ✅ **Merge immediately** - Workflows can run on hosted …
> URGENT: Use GitHub hosted runners to break chicken-and-egg cycle

- .github/runner-recovery.md
- .github/workflows/runner-builld.yaml
Fixes the rust-builder workflow that was failing because it was looking for ./infra/images/rust-builder/Dockerfile instead of ./infra/images/builder/Dockerfile.
Also disables kubectl commands on hosted runners since they don't have cluster access.
This should allow the rust-builder image to build successfully on hosted runners.
> fix: correct rust-builder dockerfile path in workflow

- .github/runner-recovery.md
- .github/workflows/runner-builld.yaml
Fixes the cache directory permission issues that were preventing builds on GitHub hosted runners.
**Changes:**
- Changed `/cache/target` to `$HOME/cache/target` for both controller and sidecar builds
- Added mkdir commands to create cache directories in user space
- This fixes the `mkdir: cannot create directory '/cache': Permission denied` errors
**Testing:**
This should allow the workflows to complete successfully on hosted runners and produce the needed images to get our self-hosted runners back online.
> fix: use HOME cache directories for hosted runners

- .github/workflows/develop-deploy.yaml
- infra/images/builder/Dockerfile
1. Fix Rust Builder Dockerfile:
- Replace hanging Helm script with direct binary download
- Use reliable get.helm.sh direct download approach
- Add version verification step
2. Fix Controller build cache directory issue:
- Add missing 'export CARGO_TARGET_DIR=/Users/jonathonfritz/cache/target'
- Align with working sidecar build pattern
- Ensures binary is built where expected for Docker context
These fixes address the two main build failures:
- Infrastructure workflow hanging at Helm install
- Deploy workflow failing to find controller binary
> fix: resolve Rust builder and controller build issues

- infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
- Add successCondition to create-coderun-resource
- Insert resolve-coderun-name step to use candidate output or label lookup
- Wire wait-for-completion and template outputs to resolved name
> fix(workflow): reliably resolve CodeRun name before waiting

- infra/charts/controller/claude-templates/code/container-rex.sh.hbs
- infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
This PR fixes two critical issues in the play workflow:
1. **Invalid successCondition causing workflow failure**
- Removed `metadata.name != ""` condition that was causing parse errors
- Kubernetes label selectors don't support != with empty strings
- The resource creation will fail naturally if unsuccessful
2. **Missing PR correlation labels**
- Rex now automatically detects and labels PRs after Claude completes
- Uses GitHub CLI to find PR by task label or branch name
- Applies `run-<workflow>` and `service-<name>` labels
- Creates labels if they don't exist
- Tested `gh pr list` commands to verify they work correctly
- The successCondition removal allows the workflow to proceed
- PR labeling ensures proper correlation for multi-agent orchestration
- Fixes workflow blocking issue …
> fix: Remove invalid successCondition and add PR correlation labels

- controller/Cargo.lock
- controller/Cargo.toml
- controller/src/tasks/code/controller.rs
- controller/src/tasks/github.rs
- controller/src/tasks/mod.rs
- controller/src/tasks/workflow.rs
This PR implements Option A: Pure Controller-Driven workflow resumption to eliminate the race condition between PR creation and workflow resumption.
- Extract workflow name from CodeRun labels or task ID
- Extract PR number from GitHub URLs
- Resume workflows via Argo API (placeholder implementation)
- Check GitHub API for PRs by branch name as fallback
- Parse repository URLs in multiple formats
- Update CodeRun status with found PR URLs
- Detect PR creation when CodeRun completes
- Handle multiple fallback strategies:
1. **Primary**: Resume immediately if PR URL is in CodeRun status
2. **Delay Check**: Wait 30s and check CodeRun again (delayed PR creation)
3. **GitHub API**: Query GitHub directly for PR by branch name
4. **Timeout**: Resume with 'no-PR' status after 60s
- Handle both …
> feat(controller): add controller-driven workflow resumption

- controller/src/tasks/code/controller.rs
The workflow resumption logic was only being called in the `CodeJobState::Completed` branch, but CodeRuns that were already 'Succeeded' took the early return path (lines 85-95) and never triggered workflow resumption.
This caused workflows to remain stuck even when CodeRuns had succeeded, because the controller would see the 'Succeeded' status and return early without calling the new workflow resumption logic.
Add workflow resumption trigger to the 'Succeeded' branch so that:
- CodeRuns that are already succeeded will trigger workflow resumption
- Handles the case where controller missed the initial completion event
- Ensures workflows progress even if controller restarts after CodeRun completion
This fixes the current test case where:
- CodeRun `coderun-implementation-task1-x5s5v` has …
> fix(controller): trigger workflow resumption for already succeeded CodeRuns

- controller/src/tasks/code/resources.rs
- infra/charts/controller/claude-templates/code/container-rex.sh.hbs
Rex was creating PRs successfully but never updating the CodeRun status with the PR URL. This caused:
- Controller timeout handler to run indefinitely 
- Workflow to remain stuck in 'Running' state
- Cleo never starting because workflow didn't progress
Rex script found and labeled PRs correctly, but never called the Kubernetes API to update the CodeRun status with the PR URL.
1. **Added environment variables** to controller job creation:
- `CODERUN_NAME`: Name of the current CodeRun resource
- `NAMESPACE`: Kubernetes namespace (via fieldRef)
2. **Enhanced Rex script** to update CodeRun status:
- After finding PR, construct PR URL
- Use `kubectl patch` to update CodeRun status with PR URL
- This triggers controller workflow resumption logic
- Rex creates PR ✅
- Rex updates CodeRun status …
> fix(rex): Add CodeRun status update with PR URL

- infra/gitops/projects/platform-project.yaml
- Add jupiter namespace to Argo CD platform project destinations
- Allows Jupiter applications to be deployed via Argo CD
- Required for external secrets to work in jupiter namespace
> feat: add jupiter namespace to platform project destinations

- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
This fixes the sensor error:
```
Internal Server Error: json: cannot unmarshal bool into Go struct field DataFilter.items.spec.dependencies.filters.data.value of type string
```
The merge-to-main sensor was using `type: bool` with `value: [true]` for the merged field filter.
Argo Events expects ALL filter values to be strings, even for boolean fields.
Changed:
- `type: bool` → `type: string`
- `value: [true]` → `value: ["true"]`
Without this fix, the sensor cannot process GitHub webhook events for merged PRs, breaking the entire automated task progression workflow.
This is a critical fix that needs to be merged ASAP.
> URGENT: Fix sensor bool type error

- infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
**Error**: `Failed: invalid spec: template name 'handle-task-completion' undefined`
**Cause**: YAML structure was broken - `templates:` section was incorrectly indented under parameters instead of spec
**Fix**: 
- Moved `templates:` to correct indentation under `spec:`
- Re-added `parameters:` section for event data binding
**Issue**: Workflows were still suspending at `wait-pr-approved` stage despite our changes to use merge-to-main
**Cause**: The play-workflow-template.yaml still had the old approval flow
**Fix**:
- Removed `wait-pr-approved` stage entirely
- Updated workflow to go directly from testing to `wait-pr-merged`
- Changed stage name from `waiting-pr-approved` to `waiting-pr-merged`
Without these fixes:
- ❌ Merge sensor creates broken workflows that immediately fail
- ❌ …
> CRITICAL FIX: Workflow template and suspend stage issues

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
Two critical workflow fixes:
1. Template error in task completion handler - fixes PR merge webhook failures
2. FIFO cleanup timing in Tess container - fixes container termination hanging
Root cause for #1: Template variables resolved in wrong context
Solution: Use template escaping to prevent early resolution
Root cause for #2: Compared working Cleo vs broken Tess  
Solution: Move FIFO cleanup to right before exit, matching Cleo pattern
Impact: Enables proper workflow resumption and clean container termination
> fix: resolve workflow resumption and container termination issues

- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
- infra/runner-cache/cache-pvc.yaml
- infra/runner-cache/values.yaml
CRITICAL BUG FIX: This fixes the root cause of the 'openssl: command not found' error in task-complete workflows.
PROBLEM: The previous fix had a bash syntax error. The syntax '[ ! command -v openssl &> /dev/null ]' doesn't work properly inside test brackets.
SOLUTION: Replaced with proper 'if ! command -v openssl >/dev/null 2>&1' syntax.
This should finally resolve the OpenSSL installation issue by ensuring proper command detection and tool installation.
> CRITICAL: Fix bash syntax causing OpenSSL installation failure

- infra/images/opencode/Dockerfile
This PR fixes the opencode Dockerfile to properly install the Open Code CLI and OpenAI Node.js SDK, addressing the build failures in the Agent Images workflow.
- Updated opencode Dockerfile to properly install Open Code CLI from https://opencode.ai/install
- Added OpenAI Node.js SDK installation for compatibility
- Simplified installation process and removed unnecessary retry logic
- Fixed Node.js SDK verification that was failing in builds
- Fixes permission denied errors when pushing to ghcr.io/5dlabs/opencode:latest
- Resolves Node.js SDK verification failures in build logs
- Ensures opencode CLI is properly installed and available
> Fix opencode Dockerfile to properly install Open Code CLI and OpenAI SDK

- infra/gitops/projects/platform-project.yaml
- Add https://kubernetes-sigs.github.io/external-dns/ to allowed repositories
- This fixes the 'repo is not permitted in project' error for external-dns application
> fix: Add external-dns Helm repository to platform project sourceRepos

- infra/gitops/applications/external-dns.yaml
- Change policy from 'sync' to 'upsert-only' to avoid conflicts with existing DNS records
- Set 'once: false' to run continuously instead of exiting on first error
- This prevents the 'Failed to do run once' fatal errors that crash the pod
- External-dns will now handle existing records gracefully and continue running
Fixes external-dns pod crash loop when encountering pre-existing DNS records.
> fix: Change external-dns policy to prevent pod crashes

- infra/gitops/resources/mailu/postgres-cluster.yaml
- Change mailu user from NOSUPERUSER to SUPERUSER
- This resolves the persistent 'permission denied for database mailu'
error when Zalando operator tries to sync prepared database schemas
- Delete existing cluster to force recreation with new permissions
The Zalando PostgreSQL operator requires SUPERUSER privileges for
the database owner to properly manage prepared databases and schemas.
> fix(mailu): grant SUPERUSER permissions to resolve schema creation

- infra/gitops/databases/mailu-postgres.yaml
- Remove explicit schemas definition from preparedDatabases
- Keep simple configuration matching vector-postgres pattern
- This should resolve the 'permission denied for database mailu' error
during prepared databases sync
The schemas section was causing permission issues during database
initialization. Using the simpler approach like vector-postgres.
> fix(mailu-postgres): remove problematic schemas configuration

- infra/gitops/applications/mailu.yaml
- Add RESOLVER_ADDRESS environment variable to admin container
- Use Google DNS (8.8.8.8) instead of Kubernetes DNS for DNSSEC validation
- This should resolve the admin container CrashLoopBackOff issue
The Kubernetes DNS service (10.96.0.10) doesn't support DNSSEC validation
which was causing the admin interface to fail startup.
> fix(mailu): resolve DNSSEC validation issue

- infra/gitops/applications/mailu.yaml
- Add DISABLE_DNSSEC_VALIDATION and SKIP_DNSSEC_VALIDATION env vars
- Try multiple approaches to disable DNSSEC validation in admin container
- This should resolve the persistent DNSSEC validation errors
> fix(mailu): add additional DNSSEC disable environment variables

- infra/gitops/applications/mailu.yaml
- Enable front.externalService with NGrok LoadBalancer for mail ports
- Configure all secure mail ports: IMAPS (993), POP3S (995), SMTP (25),
SMTPS (465), Submission (587), ManageSieve (4190)
- Disable insecure ports: IMAP (143), POP3 (110)
- Switch ingress to use NGrok ingressClassName for webmail access
- Remove NGINX-specific annotations (proxy-body-size)
This enables proper mail server exposure through NGrok TCP addresses
while maintaining secure connections for all mail protocols.
> feat(mailu): configure NGrok LoadBalancer for mail ports

- infra/gitops/applications/mailu.yaml
- Change domain from 'mail.5dlabs.ai' to '5dlabs.ai' (proper mail domain)
- Reduce hostnames to only 'mail.5dlabs.ai' to avoid DNS conflicts
- This prevents external-dns from trying to create conflicting CNAME records
for smtp.5dlabs.ai and imap.5dlabs.ai
The LoadBalancer service handles mail.5dlabs.ai for mail ports,
while ingress handles webmail.5dlabs.ai for web interface.
> fix(mailu): resolve external-dns conflicts

- infra/gitops/applications/mailu-tcp-endpoints.yaml
- infra/gitops/applications/mailu.yaml
- infra/gitops/resources/mailu-tcp-loadbalancer.yaml
- Mailu Helm chart doesn't support loadBalancerClass field
- Create dedicated LoadBalancer service with loadBalancerClass: ngrok
- Disable Helm chart's externalService (lacks NGrok support)
- Update ArgoCD app to include both TCP resources (endpoints + loadbalancer)
- This should automatically create TCP addresses in NGrok for mail ports
The loadBalancerClass field is immutable and must be set at creation time.
Helm chart template doesn't include this field, so we need a separate service.
> fix(mailu): create separate NGrok LoadBalancer for TCP addresses

- infra/gitops/applications/mailu.yaml
- Add global.database.roundcube configuration pointing to PostgreSQL
- Use roundcube.mailu-postgres.credentials secret for authentication
- This should resolve the admin pod crashes caused by missing database config
- Mailu Helm chart requires both externalDatabase (main) and global.database.roundcube
The admin pods were failing because the chart was defaulting to SQLite
instead of using the external PostgreSQL for both databases.
> fix(mailu): add Roundcube database configuration to global.database

- infra/gitops/applications/mailu.yaml
- Merge two separate admin: sections into single block
- Fixes YAML duplicate key issue where second admin: overwrote first
- Now includes both extraEnvVars AND standard admin configuration
- Should resolve SQLALCHEMY_DATABASE_URI override not being applied
Root cause: YAML duplicate keys caused extraEnvVars to be lost during Helm rendering
> fix(mailu): consolidate duplicate admin YAML keys to enable extraEnvVars

- infra/gitops/applications/mailu.yaml
- Increase admin.resources.requests to 1Gi memory and 500m CPU
- Increase admin.resources.limits to 2Gi memory and 2000m CPU
- This should resolve exit code 137 (OOM killer) during database migration
> feat(mailu): increase admin pod resources to 2Gi memory and 2 CPU

- infra/gitops/applications/mailu.yaml
- Fix incorrect indentation of resources block in admin configuration
- Properly nest requests and limits under resources
- Resolves ArgoCD ComparisonError: 'mapping values are not allowed in this context'
> fix(mailu): correct YAML indentation for admin resources

- infra/gitops/applications/mailu.yaml
- Disable livenessProbe and readinessProbe for admin pod
- This prevents pod restarts during database migration process
- Allows migration to complete without being killed by probe failures
- Can be re-enabled once database is properly initialized
> feat(mailu): disable admin probes temporarily for database migration

- infra/gitops/applications/mailu.yaml
- Enable liveness and readiness probes for admin pod
- Database migration is complete, probes will now help detect any remaining issues
- This will provide proper health monitoring for the Mailu admin service
> feat(mailu): Re-enable health probes after successful database migration

- infra/gitops/applications/mailu.yaml
- Set tls.enabled: false to prevent frontend pods from trying to mount mailu-certificates secret
- NGrok handles TLS termination externally, so Mailu doesn't need internal TLS certificates
- This should resolve the frontend pods stuck in ContainerCreating state
> fix(mailu): Disable TLS in Mailu since NGrok handles external TLS termination

- infra/gitops/applications/coredns-config.yaml
- infra/gitops/applications/mailu.yaml
- infra/gitops/resources/coredns/README.md
- infra/gitops/resources/coredns/coredns-configmap.yaml
- infra/scripts/apply-coredns-dnssec.sh
- Add CoreDNS ConfigMap with DNSSEC validation enabled
- Configure multiple upstream resolvers with health checks
- Enable DNSSEC-aware caching to prevent cache poisoning
- Update Mailu configuration to use CoreDNS instead of bypassing DNSSEC
- Add ArgoCD application for CoreDNS configuration management
- Create deployment script and documentation
Addresses CoreDNS issue #5189 and Mailu issue #2239
> feat: Enable DNSSEC validation in CoreDNS to address RFC6840 compliance

- infra/gitops/resources/coredns/README.md
- infra/gitops/resources/coredns/coredns-configmap.yaml
- Modify CoreDNS ConfigMap to disable DNSSEC validation due to compatibility issues
- Update README to reflect changes in DNS resolution strategy and configuration
- Enhance documentation for clarity on the new caching behavior and upstream resolver reliability
These changes aim to improve stability and compatibility for Talos-managed CoreDNS deployments.
> refactor: Update CoreDNS configuration to disable DNSSEC validation

- infra/gitops/applications/mailu.yaml
Helm chart repositories use semantic versions, not branch names.
> fix: use correct Mailu chart version 2.2.2 instead of 'master'

- infra/gitops/applications/mailu.yaml
- Change admin DB_PW environment variable to reference mailu-secret instead of direct PostgreSQL secret
- This ensures the admin pod uses the password managed by external-secrets
- Fixes database authentication issues after external-secrets implementation
> fix(mailu): Use external-secrets managed mailu-secret for DB_PW

- infra/gitops/applications/mailu.yaml
- Change externalDatabase.existingSecret from PostgreSQL secret to mailu-secret
- Change existingSecretPasswordKey from 'password' to 'DB_PW'
- This eliminates duplicate DB_PW environment variables and ensures consistent use of external-secrets
> fix(mailu): Update externalDatabase to use external-secrets managed secret

- infra/gitops/applications/mailu.yaml
- Change ingress host from webmail.5dlabs.ai to mail.5dlabs.ai to match NGrok endpoint
- Explicitly set backend service port to 80 (HTTP) for NGrok HTTPS termination
- Fixes NGrok gateway error ERR_NGROK_3004 by ensuring correct upstream connection
Resolves issues where NGrok was trying to connect via HTTP to HTTPS port 443,
causing invalid/incomplete HTTP response errors.
> fix(mailu): Update ingress configuration for NGrok compatibility

- infra/gitops/resources/mailu-tcp-loadbalancer.yaml
- Add argocd.argoproj.io/health-check annotation to consider NGrok LoadBalancer healthy
- NGrok manages TCP endpoints via AgentEndpoints, not traditional external IPs
- This resolves the perpetual 'Progressing' status in ArgoCD
The LoadBalancer will now show as 'Healthy' since NGrok operator is managing
the TCP endpoints correctly via AgentEndpoints.
> fix(mailu): Add custom ArgoCD health check for NGrok LoadBalancer

- infra/gitops/resources/mailu-tcp-loadbalancer.yaml
- Add comment explaining why ArgoCD shows 'Progressing' status
- NGrok LoadBalancers don't get traditional external IPs
- TCP endpoints are managed via NGrok AgentEndpoints instead
- This is expected behavior, not an issue that needs fixing
> docs(mailu): Document expected ArgoCD 'Progressing' status for NGrok LoadBalancer

- infra/gitops/applications/mailu.yaml
- Add secret.create: false to prevent Helm from managing mailu-secret
- The mailu-secret is already managed by external-secrets operator
- This resolves the OutOfSync status caused by ownership conflicts
ArgoCD was showing OutOfSync because both Helm and external-secrets
were trying to manage the same secret resource.
> fix(mailu): Disable Helm secret creation to avoid conflict with external-secrets

- infra/gitops/applications/mailu.yaml
- Change tls.flavor from default 'cert' to 'notls'
- Mailu was redirecting HTTP to HTTPS causing infinite redirect loop
- NGrok handles TLS termination, so Mailu should serve plain HTTP
Resolves ERR_TOO_MANY_REDIRECTS error when accessing mail.5dlabs.ai
> fix(mailu): Set TLS flavor to 'notls' to prevent redirect loop

- infra/gitops/applications/mailu.yaml
This should resolve the ArgoCD OutOfSync status caused by both Helm and
external-secrets trying to manage the mailu-secret.
> fix(mailu): Add secret.create: false to prevent Helm/external-secrets conflict

- infra/gitops/resources/sendgrid-dns/txt-records.yaml
- Change from headless service to LoadBalancer for TXT record support
- Add proper TXT record annotation format with quotes
- Use nonexistent selector so no pods match (DNS-only service)
> fix: Update DMARC TXT record to use LoadBalancer service

- infra/gitops/resources/cloudflare-redirects/configmap.yaml
- infra/gitops/resources/cloudflare-redirects/job.yaml
- Replace non-existent dwdraju/alpine-curl-jq:3.18 with alpine/curl:8.5.0
- Install jq via apk in the script
- Use /bin/sh instead of /bin/bash for Alpine compatibility
- Remove trailing spaces
> fix: Use working alpine/curl image and install jq

- infra/gitops/resources/sendgrid-dns/txt-records.yaml
- LoadBalancer services cannot have clusterIP: None
- Use regular ClusterIP service for TXT record via external-dns
- Remove extra quotes from TXT record annotation value
> fix: Change DMARC service from LoadBalancer to ClusterIP

- infra/gitops/resources/cloudflare-redirects/configmap.yaml
- infra/gitops/resources/cloudflare-redirects/job.yaml
- Change to alpine:3.19 base image to avoid image pull issues
- Run as root user (0) to allow apk package installation
- Install both curl and jq via apk in script
- Set readOnlyRootFilesystem: false to allow package installation
- This is acceptable for a one-time configuration job
> fix: Use alpine base image with root permissions for package installation

- infra/gitops/applications/mailu.yaml
- infra/secret-store/mailu-external-secrets.yaml
- Add SendGrid credentials to mailu-external-secrets
- Configure Postfix to use SMTP relay via environment variables
- Bypasses ISP port 25 blocking for outbound email delivery
- SendGrid API key added to secret-store/mailu-config secret
> feat(mailu): Configure SendGrid SMTP relay for outbound email

- infra/gitops/resources/mailu-ingress.yaml
- infra/gitops/resources/mailu-tcp-loadbalancer.yaml
- infra/gitops/resources/ngrok-gateway/domain.yaml
- infra/gitops/resources/ngrok-gateway/gateway.yaml
Streamline NGrok gateway configuration to focus on core functionality:
- Reduce gateway listeners to essential GitHub webhook endpoint only
- Temporarily disable Mailu TCP LoadBalancer (6 ports) for optimization
- Disable Mailu web ingress during configuration review period
- Consolidate domain resources to single active domain
- Add clear documentation for future re-enablement
This optimization maintains critical webhook functionality while allowing
for infrastructure cost analysis and planning.
Impact:
- GitHub webhooks remain fully operational
- Mail functionality temporarily available via internal access only
- Significant reduction in active NGrok endpoints
- Preserved configuration for easy restoration
> feat: optimize NGrok configuration for essential services

- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
- Remove retry strategy from merge-to-main sensor to eliminate duplicate triggers
- Add Argo Events deduplication using GitHub's unique X-GitHub-Delivery header
- Strengthen idempotency check to look for ANY existing workflow, not just Succeeded
- This prevents race conditions where duplicate workflows are created before the first reaches Succeeded status
The retry strategy was causing duplicate task-complete workflows to be created within 1 second of each other. Combined with the race condition in the idempotency check (which only looked for Succeeded workflows), this allowed both workflows to proceed in parallel, creating duplicate Rex jobs for the next task.
This fix implements the recommended best practices from multiple analyses to ensure only one workflow is created per PR merge …
> fix: prevent duplicate workflow creation on PR merge

- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
- Workflow was finding itself when checking for duplicates
- Now excludes the current workflow name from the check
- Only exits if a DIFFERENT workflow is processing the same PR
- This fixes the self-reference issue where task-complete-d6csr found itself
> fix: exclude current workflow from idempotency check

- infra/gitops/resources/github-webhooks/merge-to-main-sensor.yaml
- Use generateName with PR number appended (Argo Events documented approach)
- Add distributed lock using ConfigMap for each PR merge
- Only one workflow can process each PR merge event
- Includes stale lock detection (1 hour timeout) and automatic cleanup
- Based on actual Argo Events capabilities from documentation
- Workflow names will be like: task-complete-pr128-xxxxx
This prevents duplicate task-complete workflows from processing the same
PR merge, while not affecting the main orchestration workflow flow.
> fix: implement proper duplicate prevention with ConfigMap locks

- infra/charts/universal-app/.helmignore
- infra/charts/universal-app/Chart.yaml
- infra/charts/universal-app/templates/NOTES.txt
- infra/charts/universal-app/templates/_helpers.tpl
- infra/charts/universal-app/templates/configmap.yaml
- infra/charts/universal-app/templates/deployment.yaml
- infra/charts/universal-app/templates/externalsecret.yaml
- infra/charts/universal-app/templates/hpa.yaml
- infra/charts/universal-app/templates/ingress.yaml
- infra/charts/universal-app/templates/networkpolicy.yaml
- infra/charts/universal-app/templates/pvc.yaml
- infra/charts/universal-app/templates/service.yaml
- infra/charts/universal-app/templates/serviceaccount.yaml
- infra/charts/universal-app/templates/vault_secrets.yaml
- infra/charts/universal-app/values-task-example.yaml
- infra/charts/universal-app/values.yaml
- Adapted universal chart from 5dlabs/charts for local environment
- Replaced ALB with nginx ingress controller
- Added support for External Secrets Operator
- Added persistence and network policy templates
- Simplified environment variable handling
- Updated security contexts for standard apps
- Added example values file for task deployments
- Configured for ghcr.io registry by default
This chart will be used by Tess for deploying applications
to Kubernetes as part of the testing pipeline.
> feat: add universal-app Helm chart for standardized deployments

- controller/src/tasks/code/resources.rs
- mcp/src/main.rs
- Make requirements.yaml detection more robust
- Don't fail if current directory cannot be determined
- Skip requirements check when workspace directory is unavailable
- Prevents MCP server from crashing on startup in certain contexts
> fix: handle missing current_dir gracefully in MCP play command

- infra/charts/controller/templates/workflowtemplates/play-workflow-template.yaml
- Modified check-or-wait-for-pr to detect workflow stage
- Quality/testing stages now look for PRs with just task label
- Implementation stage still requires both task and run labels
- Fixes issue where PR_URL and PR_NUMBER were empty in quality stage
- Addresses single-repo workflow continuity with requirements.yaml
> fix: workflow PR value propagation for single-repo setups

- infra/charts/controller/templates/project-intake-template.yaml
- Use ghcr.io/5dlabs/claude:latest (has @anthropic-ai/claude-code installed)
- Remove non-existent ghcr.io/5dlabs/claude-code image reference
> fix(intake): revert to correct Claude image with Claude Code pre-installed

- controller/src/bin/test_templates.rs
- docs/requirements.yaml
Resolves the 'secret agent-admin-secrets not found' error when running play workflows.
The play MCP workflow was failing with 'secret agent-admin-secrets not found' because the docs/requirements.yaml file contained a reference to a non-existent secret.
- Removed the problematic agent-admin-secrets reference from docs/requirements.yaml
- Added clear documentation for proper secret configuration
- Fixed test_templates.rs to use correct template directory path
✅ Requirements with only environmental variables
✅ Requirements with only secrets (when they exist)
✅ No requirements at all
- docs/requirements.yaml: Removed secret reference, added documentation
- controller/src/bin/test_templates.rs: Fixed template directory path
Verified that MCP server properly handles all three requirements …
> fix: resolve requirements secret reference issue

- infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
- Fix Docker commands being interpreted as shell commands (FROM, RUN, WORKDIR, COPY)
- Fix GitHub Actions YAML being interpreted as shell commands (name:, on:, push:, branches:, jobs:, runs-on:, steps:, with:)
- Escape all backticks (\`\`\`) in heredoc sections to prevent shell interpretation
- Replace template variables with shell variables ({{pr_number}} → $PR_NUM)
- Fix inline code snippets using backticks
- This resolves the 'command not found' errors when Cleo processes CI/CD examples
The issue was that Markdown code blocks with backticks were not escaped for heredoc context, causing the shell to try to execute the code examples as actual commands instead of treating them as documentation.
> fix: escape code examples in Cleo template to prevent shell execution

- infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
- Fix GitHub Actions template variables being interpreted by shell
- Escape \$ for variables like \${{\{ github.repository \\}}}
- This prevents shell from trying to interpret \${{\{ \\}}} syntax as commands
- Resolves the 'fix: command not found' error at line 709
The issue was that GitHub Actions variables like \${{\{ github.repository \\}}} contain \$ which the shell interprets as variable substitution, even inside heredoc. These need to be escaped to prevent shell interpretation.
> fix: properly escape GitHub Actions variables in heredoc

- infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
- Fix CARGO_TARGET_DIR escaping: use \$HOME consistently in both env var and cp command
- Fix GitHub Actions variable escaping: use proper \$\\{\\{ syntax instead of over-escaped versions
- Resolve path mismatch between env var expansion and command execution
- Ensure YAML syntax is correct for GitHub Actions workflows
Addresses the issues identified in PR #557 discussion where variable escaping was inconsistent and causing malformed YAML.
> fix: correct variable escaping inconsistencies in Cleo template

- infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
- Fix Handlebars syntax errors in CI/CD examples
- GitHub Actions variables (${{\{ variable \\}}}) should remain as \${{\{ variable \\}}}
- Remove over-escaping that was causing template parsing failures
- Variables are processed by Handlebars first, then shell heredoc
- Only \$ needs escaping for shell, not GitHub Actions syntax
This resolves the 'invalid handlebars syntax' error that was preventing Cleo pods from starting.
> fix: correct GitHub Actions variable escaping in Cleo template

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
- Clean up INITIAL_GUIDANCE content before JSON processing
- Remove empty lines and trailing whitespace that cause cache_control errors
- Prevent 'cache_control cannot be set for empty text blocks' API error
- Improve Tess agent reliability and prevent workflow failures
> fix: resolve cache_control API error by cleaning empty text blocks

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
- scripts/test-all-agents-json.sh
🔧 CRITICAL FIX: PR Review Execution Issue
PROBLEM IDENTIFIED:
- PR review commands were embedded in INITIAL_GUIDANCE as text instructions
- Commands were sent to Claude but NEVER executed as shell commands
- Tess completed successfully but never actually posted PR reviews
- This was an architectural flaw, not a recent regression
SOLUTION IMPLEMENTED:
- Added actual shell commands to execute PR reviews after Claude completes
- Container now checks CI status and posts appropriate reviews:
* REQUEST CHANGES if CI missing or failing
* APPROVE if all CI checks pass
- Smart review logic based on GitHub Actions status
- Comprehensive review templates with detailed feedback
WHAT THIS FIXES:
✅ PR reviews are now actually posted (not just generated)
✅ Reviews reflect actual CI status (not just …
> fix: add actual PR review posting commands to Tess container

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
The root cause was that the script would exit early in multiple places
before reaching the sidecar shutdown code. Now using a trap on EXIT
to ensure shutdown_sidecar() is ALWAYS called no matter how or where
the script exits.
- Added shutdown_sidecar() function with all shutdown logic
- Set 'trap shutdown_sidecar EXIT' to call it on any exit
- Removed duplicate shutdown code
- Fixed indentation issues in PR review logic
- This guarantees the sidecar shutdown is attempted every time
> fix: bulletproof sidecar shutdown with EXIT trap

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
The Tess container's sidecar was not terminating, causing pods to hang indefinitely.
The script would exit early in multiple places (when GitHub CLI unavailable, no PR number, etc.) BEFORE reaching the sidecar shutdown code at the end of the script.
Implemented a bulletproof EXIT trap that ensures sidecar shutdown happens no matter how or where the script exits.
1. **Added `shutdown_sidecar()` function** - Centralized all sidecar shutdown logic
2. **Implemented EXIT trap** - Set trap for EXIT, INT, and TERM signals to call shutdown function
3. **Removed early exit statements** - Cleaned up problematic early exits that bypassed shutdown
4. **Added 30-second timeouts** - All `gh` commands now have timeouts to prevent hanging
5. **Fixed indentation issues** - Corrected nested if/else …
> fix: Tess sidecar shutdown issues with EXIT trap

- infra/charts/controller/claude-templates/code/container-rex.sh.hbs
- Add dedicated 'NON-NEGOTIABLE PULL REQUEST REQUIREMENT' section
- Make PR creation failure condition explicit and prominent
- Clarify that task completion depends entirely on PR creation
- Remove ambiguity about PR being mandatory final step
- Emphasize verification of PR creation success
This ensures Rex implementation agents cannot complete tasks without creating pull requests, which is critical for the workflow orchestration.
> feat: strengthen Rex PR creation requirement in system prompt

- infra/gitops/resources/github-webhooks/remediation-feedback-sensor.yaml
- Argo Events v1.9.7 doesn't support regex matching with '~'
- Changed to 'in' comparator for substring matching of '🔴 Required Changes'
> fix: Use 'in' comparator instead of unsupported regex '~' comparator

- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
- Converted large multi-line INITIAL_GUIDANCE string to heredoc format
- Fixes 'No: command not found' error at line 899
- Ensures proper variable expansion in guidance text
- Container already has exit 0 at end for clean termination
> fix: convert Tess INITIAL_GUIDANCE to heredoc format and ensure clean exit

- infra/gitops/rbac/argo-workflow-permissions.yaml
- Play workflow sensor creates resume workflows with argo-workflow SA
- Resume workflows need to patch suspended workflow nodes in agent-platform
- This was preventing automatic Tess startup after ready-for-qa label
- Added proper RBAC permissions for cross-namespace workflow management
> fix: add missing RoleBinding for argo-workflow ServiceAccount

- infra/gitops/rbac/argo-workflow-permissions.yaml
- Introduced a new RoleBinding to allow the argo-workflow ServiceAccount in the agent-platform namespace to create CodeRuns locally
- This enhances the permissions for the ServiceAccount, facilitating local CodeRun creation and improving workflow management
> feat: add RoleBinding for argo-workflow ServiceAccount in agent-platform

- controller/src/cli/bridge.rs
- controller/src/tasks/code/resources.rs
- controller/src/tasks/code/templates.rs
- controller/src/tasks/config.rs
- cto-config.json
- docs/agent-specific-client-config.md
- infra/charts/controller/claude-templates/code/container-cleo.sh.hbs
- infra/charts/controller/claude-templates/code/container-rex-remediation.sh.hbs
- infra/charts/controller/claude-templates/code/container-rex.sh.hbs
- infra/charts/controller/claude-templates/code/container-tess.sh.hbs
- infra/charts/controller/claude-templates/code/container.sh.hbs
- infra/charts/controller/values.yaml
- Add agent-specific tool configuration to CTO config schema
- Update Helm values to include agent tool configurations
- Modify CodeRun controller to render client-config.json per agent
- Add client-config template rendering functionality
- Update agent workspace setup to include client-config.json
- Add comprehensive tests for agent-specific tool configurations
- Update documentation for agent-specific client-config
Each agent now gets its own tailored MCP client configuration:
- Morgan: Full access (docs, web search, filesystem, git)
- Rex: Full access (backend development, rust docs, filesystem, git)
- Cleo: Full access (code quality, filesystem, git)
- Tess: Limited access (testing, basic filesystem/git)
- Cipher: No filesystem/git access (security isolation)
- Blaze: Basic access …
> feat: Add agent-specific client-config.json rendering

- infra/gitops/applications/toolman.yaml
- Introduced a new service definition for "Agent Docs" in the toolman.yaml file.
- This service serves as a documentation and knowledge base server, utilizing Docker for deployment.
- The addition enhances the toolman application by providing a dedicated resource for agent-related documentation.
> feat: Add agent-docs service to toolman configuration

- infra/gitops/applications/toolman.yaml
- Changed the transport method for the "Agent Docs" service from Docker to HTTP.
- Updated the command to use a URL for accessing the documentation server, enhancing deployment flexibility.
> fix: Update agent-docs service configuration in toolman.yaml

- mcp/src/main.rs
- Remove duplicate doc_type parameter in function call
- Rename claude_doc_type to _claude_doc_type to indicate it's unused
> fix(mcp): remove duplicate doc_type parameter and rename unused variable

- infra/gitops/applications/doc-server.yaml
- infra/gitops/databases/redis-operator-rolebinding.yaml
Fixes the Redis BRPOP command error that was occurring in the doc server worker.
The doc server worker was unable to execute BRPOP commands, showing:
```
Redis BRPOP error: unknown command `BRPOP`, with args beginning with: `queue:ingest:p5`, ...
```
The worker was connecting to Redis Sentinel (port 26379) instead of the Redis master (port 6379). Redis Sentinel doesn't support the full Redis command set including BRPOP.
1. **Added Redis Service**: Created a Kubernetes service to expose Redis master on port 6379
2. **Updated Worker Configuration**: Added worker-specific Redis URL configuration in GitOps
3. **Fixed Operator Permissions**: Added ClusterRoleBinding for Redis operator
4. **Removed Authentication**: Temporarily disabled Redis authentication for stability
- Redis master is now …
> fix: resolve Redis BRPOP error in doc server worker

- infra/gitops/applications/doc-server.yaml
Adds global Redis configuration to attempt to override the hardcoded worker Redis URL in the Helm chart.
> fix: add global Redis configuration for worker

- infra/gitops/applications/doc-server.yaml
- Add MCP_SSE_KEEPALIVE_SECS=10 to set SSE keepalive interval to 10 seconds
- This helps maintain stable Server-Sent Events connections
> feat: add MCP_SSE_KEEPALIVE_SECS configuration

- infra/gitops/applications/doc-server.yaml
- Added service configuration to exclude worker pods from service endpoints, ensuring only server pods are included.
- Configured service type as ClusterIP with specified port and targetPort.
- Introduced component label for main server pods to differentiate them from worker pods, improving resource management and clarity.
> feat: Enhance doc-server configuration with service and pod labels

- infra/charts/controller/claude-templates/docs/container.sh.hbs
- Fix jq command to handle different tasks.json structures (array vs object)
- Add robust structure detection and multiple fallback parsing strategies
- Add better error handling for base64 decoding failures
- Add debugging output to show actual tasks.json structure
- Should now process all tasks instead of just one
- Handle edge cases where task parsing fails gracefully
> fix: improve docs job task parsing and error handling

- infra/charts/controller/claude-templates/docs/container.sh.hbs
- Add support for TaskMaster's master.tasks JSON structure (10 tasks instead of 8)
- The tasks.json uses {"master": {"tasks": [...]}} structure
- Docs job should now process all 10 tasks from the intake job
- Fixed JSON parsing logic to handle the actual TaskMaster format
> fix: docs job now correctly parses TaskMaster master.tasks structure

- controller/src/tasks/code/templates.rs
- controller/src/tasks/config.rs
- controller/src/tasks/docs/templates.rs
Fixes multiple issues preventing Play workflows from executing properly:
- **Problem**: Controller failed to start with error `agents.rex.tools.localServers: missing field 'filesystem'`
- **Solution**: Made `LocalServerConfig` fields optional to handle empty `localServers: {}` configurations
- **Impact**: Controller can now parse client configs with empty local servers
- **Problem**: Cleo and Tess agents missing from Helm values, causing CodeRun failures
- **Solution**: Added complete agent configurations matching client-side config structure
- **Impact**: All Play workflow agents (Rex, Cleo, Tess) now have proper tool access
- **Problem**: Client-side tool customizations lost during Rex → Cleo → Tess workflow transitions
- **Solution**: Implemented annotation-based tool config …
> Fix Play workflow controller startup and tool config pass-through

- .github/workflows/develop-deploy.yaml
- .github/workflows/update-helm-templates.yml
- debug-play-workflow.sh
- scripts/update-templates.sh
- Added a step to regenerate Helm templates before the build process in the CI pipeline.
- Implemented a check to commit and push changes to the `claude-templates-static.yaml` if updates are detected.
- Configured Git user details for automated commits to ensure proper tracking of template changes.
This enhancement ensures that the latest templates are always used during the build, improving consistency and reducing manual intervention.
> chore: automate Helm template regeneration in CI workflow

- .github/workflows/claude-templates-update.yml
The 'Update Claude Templates' GitHub Action was failing with this error:
```
To https://github.com/5dlabs/cto
! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/5dlabs/cto'
```
This was happening because the workflow was trying to push directly to the protected main branch, which requires pull requests.
Updated the workflow to create a Pull Request instead of pushing directly to main:
- Changed from direct push to using `peter-evans/create-pull-request` action
- Added `pull-requests: write` permission for PR creation
- Workflow now creates an automated PR when ConfigMap needs updating
- PRs are properly labeled as `automated`, `charts`, and `skip-changelog`
- The workflow will now respect branch protection rules
- Automated updates will …
> fix: update Claude templates workflow to handle protected main branch

- infra/secret-store/ghcr-external-secrets.yaml
- Deleted the ExternalSecret configuration for the GitHub Container Registry in the `reason` namespace.
- This removal helps streamline the GitOps setup by eliminating an outdated configuration that is no longer needed.
> chore: remove obsolete GHCR External Secret for reason namespace

- controller/src/tasks/code/resources.rs
This commit enhances the `CodeResourceManager` by adding case-insensitive matching for CLI image keys when retrieving configurations. It introduces an optional fallback mechanism to find images that match the CLI type, improving flexibility and robustness in handling different CLI configurations. This change ensures that the correct images are utilized regardless of the case used in the CLI type specification.
> feat: improve CLI image retrieval in CodeResourceManager for case-insensitive matching

- controller/src/tasks/code/templates.rs
- controller/src/tasks/config.rs
- infra/charts/controller/agent-templates/code/codex/config.toml.hbs
- extend AgentDefinition with optional reasoning effort
- plumb controller config to pass reasoning setting into CLIConfig and Codex template
- update Codex config template to emit model_reasoning_effort when provided
- not run (config serialization change only)
> feat: add reasoning effort configuration to AgentDefinition

- controller/src/tasks/code/templates.rs
- controller/src/tasks/config.rs
- add explicit `reasoning_effort` assignments to AgentDefinition fixtures in tests
- ensures new optional field compiles and clippy passes
- cargo fmt --manifest-path controller/Cargo.toml -- --check
- cargo fmt --manifest-path mcp/Cargo.toml -- --check
- cargo clippy --manifest-path controller/Cargo.toml --all-targets -- -D warnings
- cargo clippy --manifest-path mcp/Cargo.toml --all-targets -- -D warnings
- cargo test --manifest-path controller/Cargo.toml
- cargo test --manifest-path mcp/Cargo.toml
> fix: include reasoning effort in agent test fixtures

- infra/secret-store/agent-secrets-external-secrets.yaml
Included CURSOR_API_KEY in the agent-secrets-external-secrets.yaml file to enhance the secret management for the agent. This addition ensures that the necessary API key is securely referenced from the external secrets store.
> chore(secret-store): add CURSOR_API_KEY to external secrets configuration

- infra/gitops/applications/test-db.yaml
- infra/gitops/databases/test-db/postgres.yaml
- infra/gitops/projects/platform-project.yaml
- Changed the namespace for the test PostgreSQL database in both `postgres.yaml` and `test-db.yaml` to align with the new organizational structure.
- Removed references to the old 'test-db' namespace in the platform project configuration.
This update ensures consistency across the configuration files and improves the clarity of the database environment setup.
> fix(infra): update test database namespace from 'test-db' to 'databases'

- infra/gitops/applications/database-instances.yaml
- Updated the `exclude` field in `database-instances.yaml` to prevent the deployment of the `test-db` directory, which is managed by its own application.
- This change enhances the clarity of the deployment configuration by ensuring that only relevant resources are included.
> fix(infra): exclude test-db directory from deployment in database-instances.yaml
